# Generated by Django 4.1.6 on 2023-02-16 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='article',
            field=models.CharField(default=None, max_length=20, verbose_name='Артикуль'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 19, 51, 45, 13332)),
        ),
    ]
