# Generated by Django 4.1.6 on 2023-02-19 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0002_watch_article_alter_orders_ready_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watch_img',
            field=models.ImageField(blank=True, default='photos/default_ico.png', null=True, upload_to='content/images/', verbose_name='Фотография часов'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ready_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 19, 6, 18, 246720)),
        ),
    ]
